### ISSUE TITLE
Corrections on clojure execution options post

### ISSUE THREAD

**Issue by puredanger** [practicalli/blog-content#107]
**Describe the correction**

On https://practical.li/blog/posts/clojure-which-execution-option-to-use/:

* `-A` is not deprecated (it's the only way to provide aliases when starting a repl)
* `git-resolve-tags`  should be considered deprecated (doesn't really make sense with the new git support), might just be better not to mention it as I plan to remove it
* In addition to `clojure --help` you can also `man clojure` - over time the man is likely to grow more expansive than the short help
* "directive providing a specific name for the too" - typo at the end
* `clojure -M:project/hotload:env/dev:lib/cider -P` - this won't work, -M -X and -T all scarf all subsequent arguments, so you need `clojure -P -M:project/hotload:env/dev:lib/cider`

**Mention the project maintainers**
@jr0cket

**Comment by practicalli-johnny** [comment]
I'm also adding a section on `-A` to show the purpose, now I understand it more clearly.  Thank you.
