### ISSUE TITLE
Small typo in code block

### ISSUE THREAD

**Issue by mjstra** [practicalli/blog-content#45]
**Describe the correction**
Hey, thanks for putting out all this content so far. I noticed a small typo in a code block of the 
https://practicalli.github.io/blog/posts/clojure-web-server-cli-tools-deps-edn/ article

```
(defn handler
  "A function that handles all requests from the server.
  Arguments: `req` is a ring request hash-map
  Return: ring response hash-map including :status :headers and :body"
  [req]
  {:status  200
   :headers {}}
   :body    "Hello Clojure Server world!")
```
should be 

```
(defn handler
  "A function that handles all requests from the server.
  Arguments: `req` is a ring request hash-map
  Return: ring response hash-map including :status :headers and :body"
  [req]
  {:status  200
   :headers {}
  :body    "Hello Clojure Server world!"
  })
```

Hope that helps
**Mention the project maintainers**
@jr0cket

**Comment by jr0cket** [comment]
Thank you for letting me know.  It seems my GitHub notifications need fixing, or would have seen this sooner.  Thanks again.
